version: '3.8'

services:
  app:
    build: .
    ports:
      # .env ファイルで APP_PORT=8080 のように定義
      - "${APP_PORT:-8080}:${APP_PORT:-8080}" # デフォルト値を指定する場合
    environment:
      # .env ファイルから読み込む変数を指定
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD} # パスワードも.envから読み込む
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    # env_file: # 明示的に指定することも可能
    #   - .env

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      # PostgreSQLの初期設定も.envから読み込む
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # アプリと同じパスワード変数を使用
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # .env ファイルで DB_HOST_PORT=5433 のように定義
      - "${DB_HOST_PORT:-5433}:5432" # デフォルト値を指定する場合
    # env_file: # 明示的に指定することも可能
    #   - .env

volumes:
  postgres_data:
